// ── Typography ────────────────────────────────────────────────────────────────
export const typography = {
  heading: {
    fontSize: "28px",
    fontWeight: "700",
    textAlign: "left",
    marginBottom: "4px",
    letterSpacing: "-0.5px",
    color: "#f8fafc",
    lineHeight: 1.2,
  },

  subHeading: {
    textAlign: "left",
    color: "#94a3b8",
    marginBottom: 0,
    fontSize: "14px",
    fontWeight: 400,
  },

  label: {
    fontSize: "12px",
    fontWeight: "700",
    marginBottom: "8px",
    display: "block",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.8px",
  },
};

// ── Form Elements ─────────────────────────────────────────────────────────────
export const forms = {
  input: {
    width: "100%",
    padding: "14px 18px",
    marginBottom: "20px",
    borderRadius: "12px",
    background: "rgba(0, 0, 0, 0.2)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    color: "#f8fafc",
    outline: "none",
    fontSize: "14px",
    fontFamily: "'DM Mono', monospace",
    boxSizing: "border-box",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    boxShadow: "inset 0 2px 6px rgba(15, 23, 42, 0.02)",
  },

  dropdown: {
    width: "100%",
    padding: "14px 18px",
    marginBottom: "20px",
    borderRadius: "12px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    background: "rgba(0, 0, 0, 0.2)",
    color: "#f8fafc",
    outline: "none",
    fontSize: "14px",
    fontFamily: "'DM Sans', sans-serif",
    boxSizing: "border-box",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0,0,0,0.02)",
  },

  // Compact inputs used inside endpoint/permission rows
  resourceInput: {
    flex: 2,
    padding: "11px 13px",
    borderRadius: "10px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    background: "rgba(0,0,0,0.2)",
    color: "#f8fafc",
    fontFamily: "'DM Mono', monospace",
    minWidth: "100px",
    outline: "none",
    fontSize: "13px",
    transition: "border-color 0.18s ease, box-shadow 0.18s ease",
  },

  actionDropdown: {
    flex: 1,
    padding: "11px 13px",
    borderRadius: "10px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    background: "rgba(0,0,0,0.2)",
    color: "#f8fafc",
    fontFamily: "'DM Mono', monospace",
    minWidth: "80px",
    outline: "none",
    fontSize: "13px",
    cursor: "pointer",
  },

  permissionRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "10px",
    alignItems: "center",
    background: "rgba(255, 255, 255, 0.05)",
    backdropFilter: "blur(8px)",
    padding: "16px",
    borderRadius: "14px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    flexWrap: "wrap",
  },

  removeBtn: {
    width: "34px",
    height: "34px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#ef4444",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.18s ease",
    flexShrink: 0,
  },

  addPermission: {
    background: "transparent",
    border: "1.5px dashed rgba(148, 163, 184, 0.7)",
    padding: "14px",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    marginTop: "8px",
    marginBottom: "24px",
    color: "#64748b",
    width: "100%",
    fontFamily: "'DM Sans', sans-serif",
    transition: "all 0.2s",
  },

  button: {
    width: "100%",
    padding: "16px",
    borderRadius: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    background: "linear-gradient(135deg, #334155, #475569)",
    color: "#ffffff",
    fontWeight: "700",
    fontSize: "15px",
    cursor: "pointer",
    marginTop: "16px",
    boxShadow: "0 4px 12px rgba(15, 23, 42, 0.2)",
    fontFamily: "'DM Sans', sans-serif",
    transition: "opacity 0.18s ease",
  },
};
